config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :chat_rooms
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord
	belongs_to :user
    has_many :messages, dependent: :destroy
    validates :title, presence: true
end

app/models/message.rb
class Message < ApplicationRecord
	belongs_to :user
	belongs_to :chat_room
	validates :body, presence: true, length: {minimum: 2, maximum: 1000}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

has_many :chat_rooms, dependent: :destroy
has_many :messages, dependent: :destroy


validates :first_name, :last_name, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/chat_rooms_controller.rb
class ChatRoomsController < ApplicationController

  def index
    @chat_rooms = ChatRoomDecorator.decorate_collection(ChatRoom.all)
  end

  def show
  	@chat_room = ChatRoom.find(params[:id])
  	@json_object = ChatRoomsSerializer.new(@chat_room).as_json
  end

end

app/controllers/message_controller.rb
class MessageController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chat_rooms_helper.rb
module ChatRoomsHelper
end

app/helpers/message_helper.rb
module MessageHelper
end

app/views/chat_rooms/index.html.erb
Its David fucking chat room mansion, you better recognize bitches
<br>

<% ChatRoom.all.each do |room| %>
	<a href="chat_rooms/<%= room.id %>"><%= room.title %></a>
<% end %>

app/views/chat_rooms/show.html.erb
<h2 class="text-center">
  <%= @chat_room.title %>
  <br/>
  <small>
    <%= link_to 'Back', chat_rooms_path, class: 'btn btn-primary btn-sx' %>
  </small>
</h2>

<%= react_component('ChatRoom', { chat_room: @json_object }) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsReactChatRoomChallenge</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>